force-app/main/default/objects/Contact_Person__c/Contact_Person__c.object-meta.xml
<CustomObject>
    <label>Contact Person</label>
    <nameField>
        <label>Contact Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Person__c/fields/Contact_Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Type__c</fullName>
    <label>Contact Person Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Person__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient Name</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Contact Persons</relationshipLabel>
    <relationshipName>Contact_Persons</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/ID_Series__c.field-meta.xml
<CustomField>
    <fullName>ID_Series__c</fullName>
    <label>ID Series</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipName>Pacients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Procedure__c/Patient_Procedure__c.object-meta.xml
<CustomObject>
    <label>Patient Procedure</label>
    <nameField>
        <label>Patient Procedure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Procedures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Procedure__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Patient Procedures</relationshipLabel>
    <relationshipName>Patient_Procedures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Procedure__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <label>Procedure</label>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipName>Pacient_Procedures</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <label>Procedure</label>
    <nameField>
        <label>Procedure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Procedure_Name__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Name__c</fullName>
    <label>Procedure Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/Generate_Consent_Controller.cls
public class Generate_Consent_Controller {
    
    public Patient_Procedure__c currentProcedure {get; set;}
    public List<Contact_Person__c> primaryContact {get; set;}
	public  String todayString {get; set;}
    
	/* Using the controller to get informations for the PDF form */
    public Generate_Consent_Controller (ApexPages.StandardController controller) {
        /* Get Patient's info */
        String procedureID = ApexPages.currentpage().getparameters().get('Id');
        currentProcedure = [SELECT Name, Patient__c, Patient__r.Name, Patient__r.ID_Series__c,
                            	   Procedure__c, Procedure__r.Procedure_Name__c,
                            	   Patient__r.Location__c, Patient__r.Location__r.VisitorAddressId, Patient__r.Location__r.VisitorAddress.Street, Patient__r.Location__r.VisitorAddress.City, Patient__r.Location__r.VisitorAddress.State
                            FROM Patient_Procedure__c
                            WHERE Id =: procedureID];
        
        primaryContact = [SELECT Id, Name
                          FROM Contact_Person__c
                          WHERE Contact_Person_Type__c = 'Primary' AND
                                Patient_Name__c =: currentProcedure.Patient__c];
            
            
        /* Create today string format dd.mm.yyyy */
        Date todayDate = system.today();
        String day;
        String month;
        if(todayDate.day() < 10) {
            day = '0' + String.valueOf(todayDate.day());
        }
        else
            day = String.valueOf(todayDate.day());
        if(todayDate.month() < 10) {
            month = '0' + String.valueOf(todayDate.month());
        }
        else
            month = String.valueOf(todayDate.month());
        
        todayString = day + '.' + month + '.' + String.valueOf(todayDate.year());
    }
}