force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Procedure__c/Patient_Procedure__c.object-meta.xml
<CustomObject>
    <label>Patient Procedure</label>
    <nameField>
        <label>Patient Procedure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Procedures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Procedure__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Patient Procedures</relationshipLabel>
    <relationshipName>Patient_Procedures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Procedure__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <label>Procedure</label>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipName>Pacient_Procedures</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <label>Procedure</label>
    <nameField>
        <label>Procedure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Generate_Consent_Controller_Test.cls
@isTest
public class Generate_Consent_Controller_Test {

    @isTest
    static void testingMethod() {
        Patient__c myPatient = TestClassUtils.getPatientRecordList(1, TRUE)[0];
        Procedure__c myProcedure = TestClassUtils.getProcedureRecordList(1, 'Abdominoplastie', TRUE)[0];
        Patient_Procedure__c myPatientProcedure = TestClassUtils.getPatientProcedureRecordList(1, myPatient.Id, myProcedure.Id, TRUE)[0];
        
        Test.startTest();
        	/* Testing the custom controller */
            PageReference defaultPage = new PageReference('/apex/Lightning_Consent_Form');
            Test.setCurrentPage(defaultPage);
            defaultPage.getParameters().put('Id', myPatientProcedure.Id);
            ApexPages.StandardController sc = new ApexPages.StandardController(myPatientProcedure);
            Generate_Consent_Controller controller = new Generate_Consent_Controller(sc); 
        
        Test.stopTest();
    }
}