force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <inlineHelpText>Cm</inlineHelpText>
    <label>Height</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Insurance_Type__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Type__c</fullName>
    <label>Insurance Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <label>Insured</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient_Procedure__c/Patient_Procedure__c.object-meta.xml
<CustomObject>
    <label>Patient Procedure</label>
    <nameField>
        <label>Patient Procedure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Procedures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Procedure__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Patient Procedures</relationshipLabel>
    <relationshipName>Patient_Procedures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Procedure__c/fields/Procedure__c.field-meta.xml
<CustomField>
    <fullName>Procedure__c</fullName>
    <label>Procedure</label>
    <referenceTo>Procedure__c</referenceTo>
    <relationshipName>Pacient_Procedures</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Procedure__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medical Procedure</fullName>
            </value>
            <value>
                <fullName>Post-Processing Acquisition Procedure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <label>Procedure</label>
    <nameField>
        <label>Procedure</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Procedure_Name__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Name__c</fullName>
    <label>Procedure Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TestClassUtils.cls
global class TestClassUtils {

    public static User getUser(String profileName, String FirstName, String LastName, Boolean isInsert) {
        Profile p = [SELECT Id FROM Profile WHERE Name =: profileName];
        
        User newUser = new User(
            Alias = 'standt', 
            Email = 'standarduser@testorg.com', 
            EmailEncodingKey = 'UTF-8',
            FirstName = FirstName,
            LastName = LastName, 
            LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey = 'America/Los_Angeles', 
            UserName = profileName.replaceAll('\\s+','') + FirstName.replaceAll('\\s+','') + LastName.replaceAll('\\s+','') + '@testorg.com');
        
        if(isInsert)
            insert newUser;
        
        return newUser;
    }
    
    public static List<Patient__c> getPatientRecordList(Integer size, Boolean isInsert)
    {
        List<Patient__c> patients = new List<Patient__c>();
        for(Integer i = 0; i < size; i++) {
            Patient__c p = new Patient__c();
            p.Name = 'Test Patient' + i;
            p.Sex__c = 'Female';
            p.Insured__c = 'Yes';
            p.Insurance_Type__c = 'Private';
            p.Weight__c = 50;
            p.Height__c = 150;   
                
            patients.add(p);
        }
        
        if(isInsert)
            insert patients;
        
        return patients;
    }
    
    public static List<Procedure__c> getProcedureRecordList(Integer size, String Name, Boolean isInsert)
    {
        List<Procedure__c> procedures = new List<Procedure__c>();
        for(Integer i = 0; i < size; i++) {
			Procedure__c p = new Procedure__c();
            p.Name = 'Test Procedure' + i;
            p.Procedure_Name__c = Name;
            p.Type__c = 'Medical Procedure';
            
            procedures.add(p);
        }
        
        if(isInsert)
            insert procedures;
        
        return procedures;
    }
    
    public static List<Patient_Procedure__c> getPatientProcedureRecordList(Integer size, String PatientID, String ProcedureID, Boolean isInsert)
    {
        List<Patient_Procedure__c> PatientProcedures = new List<Patient_Procedure__c>();
        for(Integer i = 0; i < size; i++) {
			Patient_Procedure__c pp = new Patient_Procedure__c();
            pp.Name = 'Test Pacient Procedure' + i;
            pp.Procedure__c = ProcedureID;
            pp.Patient__c = PatientID;
            
            PatientProcedures.add(pp);
        }
        
        if(isInsert)
            insert PatientProcedures;
        
        return PatientProcedures;
    }
}